
[build-system]
requires = [
    "wheel",
    "Cython==3.0.11",
    "setuptools>=62.4",
]


[project]
name = 'selectolax'
version = '0.3.29'
description = 'Fast HTML5 parser with CSS selectors.'
readme = 'README.rst'
requires-python = '>=3.8'
license = {file = 'LICENSE'}
authors = [
    {name = 'Artem Golubin', email = 'me@rushter.com'}
]
dependencies = [
   "Cython==3.0.11",
]

[tool.cibuildwheel]
build-frontend = "build"
build-verbosity = 1


skip = [
    "*-manylinux_i686",
    "*-musllinux_i686",
    "*-win32",
    "*-musllinux*",
    "pp*"
]
macos.archs = ["x86_64", "arm64"]
test-skip = "*-macosx_arm64"
